[2023-08-13T18:22:56.810+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrPipeline.validate_file manual__2023-08-13T18:21:18+00:00 [queued]>
[2023-08-13T18:22:56.886+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrPipeline.validate_file manual__2023-08-13T18:21:18+00:00 [queued]>
[2023-08-13T18:22:56.926+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-13T18:22:57.002+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_file> on 2023-08-13 18:21:18+00:00
[2023-08-13T18:22:57.070+0000] {standard_task_runner.py:57} INFO - Started process 14016 to run task
[2023-08-13T18:22:57.110+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrPipeline', 'validate_file', 'manual__2023-08-13T18:21:18+00:00', '--job-id', '1116', '--raw', '--subdir', 'DAGS_FOLDER/emr.py', '--cfg-path', '/tmp/tmpgajo0m98']
[2023-08-13T18:22:57.114+0000] {standard_task_runner.py:85} INFO - Job 1116: Subtask validate_file
[2023-08-13T18:22:57.338+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-13T18:22:57.675+0000] {task_command.py:410} INFO - Running <TaskInstance: emrPipeline.validate_file manual__2023-08-13T18:21:18+00:00 [running]> on host 484e6be077e8
[2023-08-13T18:22:58.600+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emrPipeline' AIRFLOW_CTX_TASK_ID='validate_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-13T18:21:18+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-13T18:21:18+00:00'
[2023-08-13T18:22:58.602+0000] {logging_mixin.py:150} INFO - Reading the file
[2023-08-13T18:22:58.652+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-08-13T18:22:58.652+0000] {logging_mixin.py:150} INFO - {"region_name": "us-east-1"}
[2023-08-13T18:22:58.711+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2023-08-13T18:22:59.375+0000] {logging_mixin.py:150} INFO - VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type
[2023-08-13T18:22:59.400+0000] {python.py:183} INFO - Done. Returned value was: False
[2023-08-13T18:22:59.511+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=emrPipeline, task_id=validate_file, execution_date=20230813T182118, start_date=20230813T182256, end_date=20230813T182259
[2023-08-13T18:22:59.641+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-13T18:22:59.825+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
