[2023-08-02T17:00:14.384+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-02T17:00:14.450+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: userCase2.s3_file_check scheduled__2023-08-02T16:00:00+00:00 [queued]>
[2023-08-02T17:00:14.459+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: userCase2.s3_file_check scheduled__2023-08-02T16:00:00+00:00 [queued]>
[2023-08-02T17:00:14.459+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-08-02T17:00:14.477+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): s3_file_check> on 2023-08-02 16:00:00+00:00
[2023-08-02T17:00:14.485+0000] {standard_task_runner.py:57} INFO - Started process 1556 to run task
[2023-08-02T17:00:14.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'userCase2', 's3_file_check', 'scheduled__2023-08-02T16:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/userCase.py', '--cfg-path', '/tmp/tmp2s6ws2mh']
[2023-08-02T17:00:14.495+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask s3_file_check
[2023-08-02T17:00:14.509+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-02T17:00:14.549+0000] {task_command.py:410} INFO - Running <TaskInstance: userCase2.s3_file_check scheduled__2023-08-02T16:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-02T17:00:14.562+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-02T17:00:14.651+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='userCase2' AIRFLOW_CTX_TASK_ID='s3_file_check' AIRFLOW_CTX_EXECUTION_DATE='2023-08-02T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-02T16:00:00+00:00'
[2023-08-02T17:00:14.653+0000] {s3.py:103} INFO - Poking for key : s3://myawsbucket19080/raw/movies.csv
[2023-08-02T17:00:14.665+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-08-02T17:00:14.666+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-08-02T17:00:15.252+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2023-08-02T17:00:15.262+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=userCase2, task_id=s3_file_check, execution_date=20230802T160000, start_date=20230802T170014, end_date=20230802T170015
[2023-08-02T17:00:15.305+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-02T17:00:15.335+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
