[2023-08-13T17:28:35.937+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrPipeline.step_checker_hive_task manual__2023-08-13T17:28:01+00:00 [queued]>
[2023-08-13T17:28:36.110+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrPipeline.step_checker_hive_task manual__2023-08-13T17:28:01+00:00 [queued]>
[2023-08-13T17:28:36.110+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-13T17:28:36.438+0000] {taskinstance.py:1327} INFO - Executing <Task(EmrStepSensor): step_checker_hive_task> on 2023-08-13 17:28:01+00:00
[2023-08-13T17:28:36.509+0000] {standard_task_runner.py:57} INFO - Started process 12312 to run task
[2023-08-13T17:28:36.601+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrPipeline', 'step_checker_hive_task', 'manual__2023-08-13T17:28:01+00:00', '--job-id', '1066', '--raw', '--subdir', 'DAGS_FOLDER/emr.py', '--cfg-path', '/tmp/tmpufq3okwi']
[2023-08-13T17:28:36.604+0000] {standard_task_runner.py:85} INFO - Job 1066: Subtask step_checker_hive_task
[2023-08-13T17:28:36.745+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-13T17:28:37.556+0000] {task_command.py:410} INFO - Running <TaskInstance: emrPipeline.step_checker_hive_task manual__2023-08-13T17:28:01+00:00 [running]> on host 484e6be077e8
[2023-08-13T17:28:38.996+0000] {abstractoperator.py:594} ERROR - Exception rendering Jinja template for task 'step_checker_hive_task', field 'step_id'. Template: "{{ task_instance.xcom_pull(task_ids='step_adder', key='return_value')[0] }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-08-13T17:28:38.998+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: None has no element 0
[2023-08-13T17:28:39.035+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=emrPipeline, task_id=step_checker_hive_task, execution_date=20230813T172801, start_date=20230813T172835, end_date=20230813T172839
[2023-08-13T17:28:39.169+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1066 for task step_checker_hive_task (None has no element 0; 12312)
[2023-08-13T17:28:39.300+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-13T17:28:39.532+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
