[2023-08-02T17:00:01.824+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-02T17:00:01.885+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: userCase2.S5 scheduled__2023-08-02T16:00:00+00:00 [queued]>
[2023-08-02T17:00:01.901+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: userCase2.S5 scheduled__2023-08-02T16:00:00+00:00 [queued]>
[2023-08-02T17:00:01.901+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T17:00:01.927+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): S5> on 2023-08-02 16:00:00+00:00
[2023-08-02T17:00:01.938+0000] {standard_task_runner.py:57} INFO - Started process 1544 to run task
[2023-08-02T17:00:01.945+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'userCase2', 'S5', 'scheduled__2023-08-02T16:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/userCase.py', '--cfg-path', '/tmp/tmpph01b8a3']
[2023-08-02T17:00:01.948+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask S5
[2023-08-02T17:00:01.977+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-02T17:00:02.024+0000] {task_command.py:410} INFO - Running <TaskInstance: userCase2.S5 scheduled__2023-08-02T16:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-02T17:00:02.074+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-02T17:00:02.178+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='userCase2' AIRFLOW_CTX_TASK_ID='S5' AIRFLOW_CTX_EXECUTION_DATE='2023-08-02T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-02T16:00:00+00:00'
[2023-08-02T17:00:02.180+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-02T17:00:02.181+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 10']
[2023-08-02T17:00:02.202+0000] {subprocess.py:86} INFO - Output:
[2023-08-02T17:00:12.233+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-02T17:00:12.265+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=userCase2, task_id=S5, execution_date=20230802T160000, start_date=20230802T170001, end_date=20230802T170012
[2023-08-02T17:00:12.330+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-02T17:00:12.358+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
